# Generated by Django 5.1.15 on 2026-07-05 15:04

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='订单号')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='总金额')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='折扣金额')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='实付金额')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], db_index=True, default='pending', max_length=20, verbose_name='订单状态')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'db_table': 'biz_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_id', models.UUIDField(verbose_name='商品 ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='小计')),
            ],
            options={
                'verbose_name': '订单项',
                'verbose_name_plural': '订单项列表',
                'db_table': 'biz_order_item',
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('payment_method', models.CharField(max_length=20, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, verbose_name='交易号')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
                'db_table': 'biz_payment_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
