# Generated by Django 5.1.15 on 2026-07-05 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='用户名')),
                ('action', models.CharField(db_index=True, max_length=20, verbose_name='操作类型')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='操作模型')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='对象 ID')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='变更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('status', models.CharField(default='success', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
