# Generated by Django 5.1.15 on 2026-07-05 15:04

import apps.files.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('original_name', models.CharField(max_length=500, verbose_name='原始文件名')),
                ('file', models.FileField(max_length=500, upload_to=apps.files.models.upload_path, verbose_name='文件')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('file_type', models.CharField(choices=[('image', 'IMAGE'), ('document', 'DOCUMENT'), ('video', 'VIDEO'), ('audio', 'AUDIO'), ('other', 'OTHER')], default='other', max_length=20, verbose_name='文件分类')),
                ('md5', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='MD5')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件列表',
                'db_table': 'sys_file',
                'ordering': ['-created_at'],
            },
        ),
    ]
